"""Added estado_civil to User

Revision ID: 11a9c1c92a57
Revises: 3a6c0ea8995a
Create Date: 2024-05-03 21:31:53.654419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a9c1c92a57'
down_revision = '3a6c0ea8995a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_civil', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('estado_civil')

    # ### end Alembic commands ###
