"""Added conjuge model

Revision ID: 33521f9dbc70
Revises: 11a9c1c92a57
Create Date: 2024-05-17 21:27:46.858526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33521f9dbc70'
down_revision = '11a9c1c92a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('conjuge_data_nascimento')
        batch_op.drop_column('conjuge_rg')
        batch_op.drop_column('conjuge_nome')
        batch_op.drop_column('conjuge_cpf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conjuge_cpf', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('conjuge_nome', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('conjuge_rg', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('conjuge_data_nascimento', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
