"""Adiciona colunas do cônjuge

Revision ID: 3a6c0ea8995a
Revises: 719364540437
Create Date: 2024-05-03 16:18:46.309859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6c0ea8995a'
down_revision = '719364540437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conjuge_cpf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('conjuge_rg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('conjuge_data_nascimento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('conjuge_data_nascimento')
        batch_op.drop_column('conjuge_rg')
        batch_op.drop_column('conjuge_cpf')

    # ### end Alembic commands ###
