"""Add conjuge_nome and filhos_nomes columns

Revision ID: 719364540437
Revises: 
Create Date: 2024-05-03 08:41:44.444697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719364540437'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conjuge_nome', sa.String(length=100), nullable=True))
        batch_op.alter_column('telefone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('conjuge_nome')

    # ### end Alembic commands ###
